---
title: "Basic group summary"
author: "Annemarie"
date: "25/05/2020"
output: html_document
---


#Load packages
```{r}
library(dplyr)
library(tidyr)
library(reshape2)
```


## import data

```{r}
# path
#outer.loc <- "C:/Users/Liz/Dropbox/Cincy JOB/FL Fieldwork/" #Liz laptop path
outer.loc<- "C:/Users/avdma/Dropbox/" # Annemarie laptop
data.loc <- "2020 field season/ANALYSIS/"


# crowd + displacement period file
raw.per0.dyad.aggDC <- read.csv(paste0(outer.loc, data.loc, "per0.dyad.aggDC.csv")) %>%
  rename(orderkey=X)

per0.dyad.aggDC<-raw.per0.dyad.aggDC # copy file --> this will be your working file, so if you make a mistake you always have your raw file without having to import it again
```



## summarize displacements and crowds + total per first/last/all days
```{r}
sum.per0.aggDC <- per0.dyad.aggDC %>%
  group_by(period) %>%
  summarise(ncrowd=sum(crowd), ndisplace=sum(displace)) %>%
  mutate(totalDC=ncrowd+ndisplace)

sum.per0days.aggDC <- per0.dyad.aggDC %>%
  group_by(period, days) %>%
  summarise(ncrowd=sum(crowd), ndisplace=sum(displace)) %>%
  mutate(totalDC=ncrowd+ndisplace)

summary.per0.aggDC<-bind_rows(sum.per0.aggDC,sum.per0days.aggDC) %>%
  mutate(propcrowd=ncrowd/totalDC, propdisplace=ndisplace/totalDC) # or would it be better to get proportion over all interactions?
summary.per0.aggDC
```

