---
title: 'Pool vs separate: summarize ref model STRATEGIES'
author: "Liz Hobson"
date: "May 28, 2020"
output: html_document
---

#Load packages and helper code
```{r}
library(dplyr)
library(reshape2)

#install_github("danm0nster/domstruc")
library(domstruc)

```

#Import data & process

```{r}
#reference model data
EXPLORE_refmodeldata <- read.csv(file="EXPLORE-refmodeldata.csv")
head(EXPLORE_refmodeldata)

ref.model <- EXPLORE_refmodeldata #update name here when changing to ANALYZE ref model

#observed data
observed.summary <- read.csv(file="EXPLORE-SUMM.observed.csv")
head(observed)
```


#Find strategies (takes awhile!)
```{r}
#run.s #list of all run names
#head(ref.model)
#head(EXPLORE_refmodelCOR_CxD)

run.s <- as.character(unique(ref.model$runID))
n.total.dyads <- 420 #change this if the total number of dyads changes (group size !=21)
replicates <- 100 #how many runs of the reference model were done

#make empty dataframe to fill
ref.model.strategies <- data.frame(run.code=character(), 
                                   type=character(), 
                                   focus.Rcrowd=numeric(), 
                                   position.Rcrowd=numeric(), 
                                   strategy.Rcrowd=numeric(), 
                                   fp.Rdisp=numeric(), 
                                   strategy.Rdisp=numeric()
                                  )

refmodel.blurdata <- data.frame(runID=character(),
                                type=character(),
                                blur=numeric(),
                                focus=numeric(),
                                focus_ci_hi=numeric(),
                                focus_ci_lo=numeric(),
                                position=numeric(),
                                position_ci_hi=numeric(),
                                position_ci_lo=numeric()
                                )
#run=2

#n.Ocrowd <- sum(run.data$observed.crowd)
#n.Odisplace <- sum(run.data$observed.displace)
start.time <- Sys.time()

for(run in 1:replicates){
  run.code <- run.s[run]
  print(run.code)
  run.data <- subset(ref.model, runID==run.code)

  ref.modelW0s <- merge(dyad.list, run.data, all.x=TRUE,
                       by=c("actor", "subject")) #head(run.dataW0s)
  
  #print a check
  check <- length(ref.modelW0s$actor)
  print(check)
  
  #make runID character (not factor)
  ref.modelW0s$runID <- as.character(ref.modelW0s$runID)
 
   #fill newly-merged data with 0's where no interactions
  ref.modelW0s[is.na(ref.modelW0s)] <- 0
  
  ### CROWD
  
  ref.crowd.mx <- reshape2::dcast(ref.modelW0s, actor~subject, value.var="random.crowd") #head(ref.crowd.mx)
  ref.crowd.mx[is.na(ref.crowd.mx)] <- 0 #for linearity measure, matrix needs to be fully filled, no NAs
  ref.crowd.mx <- matrix.please(ref.crowd.mx)
  
  #CROWDS
# Compute focus & position
  focus.Rcrowd <- dom_focus(ref.crowd.mx)
  position.Rcrowd <- dom_position(ref.crowd.mx)
  fp.Rcrowd <- cbind.data.frame(focus.Rcrowd, position.Rcrowd)
  colnames(fp.Rcrowd) <- c("focus", "position")
  
  #Compute blur models
  blur.Rcrowd <- dom_make_blur_data(ref.crowd.mx)
  
  #compile crowd summary
  runID <- rep(run.code, length(blur.Rcrowd$blur))
  type <- rep("crowd", length(blur.Rcrowd$blur))
  blur.crowd <- cbind.data.frame(runID, type, blur.Rcrowd)
  
  #Find strategy
  strategy.Rcrowd <- dom_categorize_strategy(data=fp.Rcrowd, blur_data=blur.Rcrowd)
  
  
  ### DISPLACEMENT
  
  ref.disp.mx <- reshape2::dcast(ref.modelW0s, actor~subject, value.var="random.displace") #head(ref.disp.mx)
  ref.disp.mx[is.na(ref.disp.mx)] <- 0
  ref.disp.mx <- matrix.please(ref.disp.mx)
  
  # DISPLACEMENTS
  # Compute focus & position
  focus.Rdisp <- dom_focus(ref.disp.mx)
  position.Rdisp <- dom_position(ref.disp.mx)
  fp.Rdisp <- cbind.data.frame(focus.Rdisp, position.Rdisp)
  colnames(fp.Rdisp) <- c("focus", "position")

  #Compute blur models
  blur.Rdisp <- dom_make_blur_data(ref.disp.mx)

  #compile displace summary
  runID <- rep(run.code, length(blur.Rdisp$blur))
  type <- rep("displace", length(blur.Rdisp$blur))
  blur.displace <- cbind.data.frame(runID, type, blur.Rdisp)
  
  #Find strategy
  strategy.Rdisp <- dom_categorize_strategy(data=fp.Rdisp, blur_data=blur.Rdisp)
  
  
  ### POOL ALL DATA
  
  #pool blur data
  refmodel.blurdata <- rbind.data.frame(refmodel.blurdata, blur.crowd, blur.displace)
  
  #pool strategy/run data
  run.strategy.sums <- cbind.data.frame(run.code, 
                                        focus.Rcrowd, position.Rcrowd, strategy.Rcrowd, 
                                        focus.Rdisp, position.Rdisp, strategy.Rdisp
                                        )
  
  ref.model.strategies <- rbind(ref.model.strategies, run.strategy.sums)

  
}

end.time <- Sys.time()

#Time to run:
end.time - start.time

#t(ref.model.summaries)
head(ref.model.summaries)

#WRITE DATA
dfile.loc <- "C:/Users/Liz/Dropbox/A ACTIVE MSs/2020-05 Pool vs separate behaviors/pool-separate-behaviors/"
#write.csv(ref.model.summaries, file = paste(dfile.loc, "EXPLORE_SUMM.refmodel.strategies.csv", sep=""))	
#write.csv(refmodel.blurdata, file = paste(dfile.loc, "EXPLORE_SUMM.refmodel.blurs.csv", sep=""))	

```

