---
title: 'Pool vs separate: summarize ref model CORRELATIONS'
author: "Liz Hobson"
date: "May 28, 2020"
output: html_document
---


#Load packages and helper code
```{r}
library(plyr)
```


#Import data & process

```{r}
#load the reference model data
EXPLORE_refmodeldata <- read.csv(file="EXPLORE-refmodeldata.csv")
head(EXPLORE_refmodeldata)

ref.model <- EXPLORE_refmodeldata #update name here when changing to ANALYZE ref model
```


# how are displacements and crowds correlated in the random runs?
NOTE: the package plyr conflicts with the package dplyr causing some weird behavior. Be VERY CAREFUL if you are using both! You can use detach(package:plyr) to de-activate plyr later in a script

```{r}
head(ref.model)

require(plyr)
func <- function(ref.model)
{
return(data.frame(COR = cor(ref.model$random.displace, ref.model$random.crowd)))
}

COR.refmodel <- ddply(ref.model, .(runID), func)

#find observed correlation between number of crowds and number of displacements
COR.observed <- cor(ref.model$observed.crowd, ref.model$observed.displace)

#find mean of reference model correlations
COR.refmodel.mean <- mean(COR.refmodel$COR)


#PLOT
par(mfrow=c(1,1))

run.s <- unique(ref.model$runID)

for(run in 1:replicates){
  run.code <- run.s[run]
  run.data <- subset(ref.model, runID==run.code)
  run.corr <- subset(COR.random, runID==run.code)
  with (run.data, plot (random.displace, random.crowd, main=paste0(run.code, " Correlation=", round(run.corr$COR, 2))))
  with (run.data, abline(lm(random.crowd~random.displace), col="grey")) # regression line (y~x)
}

#WRITE DATA 
dfile.loc <- "C:/Users/Liz/Dropbox/A ACTIVE MSs/2020-05 Pool vs separate behaviors/pool-separate-behaviors/"
#dfile.loc <- YOUR LOCATION HERE

#write.csv(COR.random, file = paste(dfile.loc, "EXPLORE_refmodelCOR_CxD.csv", sep=""))	


```

